before_install:
  - chmod +x mvnw
language: java
jdk:
  - oraclejdk8
sudo: false
script: mvn clean verify
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: stones-game-java